// Core data model for the RAG dashboard.

export type MediaType =
  | 'youtube'
  | 'image'
  | 'audio'
  | 'document'
  | 'text'
  | 'website';

export type MediaStatus = 'processing' | 'indexed' | 'failed';

export interface MediaItem {
  id: string;
  type: MediaType;
  name: string;
  description: string;
  /** ISO date string (YYYY-MM-DD) the user can edit. */
  date: string;
  status: MediaStatus;
  /** Number of vector chunks this item produced once indexed. */
  chunks: number;
  /** Short preview / extracted text used for the "copy content" action. */
  content: string;
  /** Type-specific source reference (URL for youtube/website, filename for files). */
  source?: string;
  /** Preview image for the card chip — YouTube thumbnail, or a hosted image URL
   *  for image sources. Absent for text/docs (they show a title only). */
  thumbnail?: string;
  /** Approximate size label, e.g. "2.4 MB" or "312 pages". */
  sizeLabel?: string;
  /** User's freeform note on this source (schema v2 `user_note`). */
  userNote?: string;
  /** For YouTube: duration label like "12:04". For audio: same. */
  durationLabel?: string;
  /** Why indexing failed (shown on the failed chip/row); cleared on retry. */
  error?: string;
}

export interface Prompt {
  id: string;
  title: string;
  body: string;
  /** Optional emoji/icon shown on the prompt card. */
  icon?: string;
  /** True for the built-in starter prompts. */
  builtIn?: boolean;
}

/**
 * A reusable ANSWERING PERSONA — a name + a robot/emoji icon + a system
 * prompt. Dragged onto the board as a node and wired into a brain, its
 * system prompt rides into that brain's answer as guidance (functionally a
 * re-skin of a Prompt piece). Never a source, never indexed.
 */
export interface Agent {
  id: string;
  name: string;
  /** Optional emoji/icon shown on the agent card and node (defaults to 🤖). */
  icon?: string;
  /** Optional uploaded image (small data URL) — wins over `icon` when set. */
  avatar?: string;
  /** The persona's system prompt — steers HOW a wired brain answers. */
  systemPrompt: string;
  /** True for the built-in starter agents. */
  builtIn?: boolean;
}

export type QueryScope = 'selected' | 'everything';

export interface Citation {
  mediaId: string;
  mediaName: string;
  type: MediaType;
  /** e.g. "p. 42", "4:31", "81%" */
  locator: string;
  snippet: string;
  /** Similarity score 0-1 (from Pinecone cosine distance). */
  score?: number;
  /** Seconds from start — enables ?t= jump links for youtube, seek for audio. */
  startSec?: number;
  /** Fully-formed jump URL (youtube: ?t=..., others: undefined). */
  jumpUrl?: string;
}

/** How an attachment participates: one-off discussion vs permanent indexing. */
export type AttachmentMode = 'discuss' | 'index';

export interface ChatAttachment {
  name: string;
  mode: AttachmentMode;
  kind: 'image' | 'file';
}

/** A mock generated image (NanoBanana / Kling) shown as a card in chat. */
export interface GeneratedImage {
  prompt: string;
  model: 'nanobanana' | 'kling';
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  citations?: Citation[];
  /** True when retrieval was weak/empty for this answer (no-match guardrail). */
  noMatch?: boolean;
  /** Follow-up questions (generated by Make) shown as clickable chips. */
  suggestedQuestions?: string[];
  /** Media ids that were in context when this message was sent. */
  contextIds?: string[];
  /** Transient: true while this answer is still streaming in, so the renderer
   *  holds heavy diagram/chart blocks until their fence closes. Not persisted. */
  streaming?: boolean;
  attachment?: ChatAttachment;
  image?: GeneratedImage;
  createdAt: string;
}

export interface Conversation {
  id: string;
  projectId: string;
  title: string;
  pinned: boolean;
  messages: ChatMessage[];
  createdAt: string;
  updatedAt: string;
}

export interface Project {
  id: string;
  name: string;
  icon: string;
  description: string;
  /** Which library sources belong to this project. */
  sourceIds: string[];
  createdAt: string;
}

export interface Note {
  id: string;
  projectId: string;
  content: string;
  citations?: Citation[];
  createdAt: string;
}
