// Core data model for the RAG dashboard.

export type MediaType =
  | 'youtube'
  | 'image'
  | 'audio'
  | 'document'
  | 'text'
  | 'website';

export type MediaStatus = 'processing' | 'indexed' | 'failed';

export interface MediaItem {
  id: string;
  type: MediaType;
  name: string;
  description: string;
  /** ISO date string (YYYY-MM-DD) the user can edit. */
  date: string;
  status: MediaStatus;
  /** Number of vector chunks this item produced once indexed. */
  chunks: number;
  /** Short preview / extracted text used for the "copy content" action. */
  content: string;
  /** Type-specific source reference (URL for youtube/website, filename for files). */
  source?: string;
  /** Approximate size label, e.g. "2.4 MB" or "312 pages". */
  sizeLabel?: string;
  /** User's freeform note on this source (schema v2 `user_note`). */
  userNote?: string;
  /** For YouTube: duration label like "12:04". For audio: same. */
  durationLabel?: string;
}

export interface Prompt {
  id: string;
  title: string;
  body: string;
  /** Optional emoji/icon shown on the prompt card. */
  icon?: string;
  /** True for the built-in starter prompts. */
  builtIn?: boolean;
}

export type QueryScope = 'selected' | 'everything';

export interface Citation {
  mediaId: string;
  mediaName: string;
  type: MediaType;
  /** e.g. "p. 42", "04:31", "§3" */
  locator: string;
  snippet: string;
}

/** How an attachment participates: one-off discussion vs permanent indexing. */
export type AttachmentMode = 'discuss' | 'index';

export interface ChatAttachment {
  name: string;
  mode: AttachmentMode;
  kind: 'image' | 'file';
}

/** A mock generated image (NanoBanana / Kling) shown as a card in chat. */
export interface GeneratedImage {
  prompt: string;
  model: 'nanobanana' | 'kling';
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  citations?: Citation[];
  /** True when retrieval was weak/empty for this answer (no-match guardrail). */
  noMatch?: boolean;
  /** Follow-up questions (generated by Make) shown as clickable chips. */
  suggestedQuestions?: string[];
  /** Media ids that were in context when this message was sent. */
  contextIds?: string[];
  attachment?: ChatAttachment;
  image?: GeneratedImage;
  createdAt: string;
}

export interface Conversation {
  id: string;
  projectId: string;
  title: string;
  pinned: boolean;
  messages: ChatMessage[];
  createdAt: string;
  updatedAt: string;
}

export interface Project {
  id: string;
  name: string;
  icon: string;
  description: string;
  /** Which library sources belong to this project. */
  sourceIds: string[];
  createdAt: string;
}

export interface Note {
  id: string;
  projectId: string;
  content: string;
  citations?: Citation[];
  createdAt: string;
}
