/**
 * App build number — displayed at the bottom of the olive rail.
 *
 * BUMP RULES (user directive 2026-07-05):
 *   +0.1 — every shipped change set (bug fix, feature, tuning)
 *   +1.0 — major reconstructions
 * Baseline: 3.5 declared 2026-07-05.
 * 3.6 — 2026-07-05: stack privacy (engine aliases, guardrail on every answer path), top-right stamp removed, manual refreshed.
 * 3.7 — 2026-07-05: villain decoy codenames over the wire; real ids resolve server-side only (model-map.server.ts).
 * 3.8 — 2026-07-05: project switcher capped (~8 visible, scroll to 13, View all beyond).
 * 3.9 — 2026-07-05: Olive Grove beauty pass (warm tokens, layered shadows, sunlit rail, olive dot grid, jewel zoom controls) + answersDoc wordmark under the top-right menu.
 * 3.10 — 2026-07-05: connected agents — board robot edits write through to the Agents page and back; copies on the board stay in sync.
 * 3.11 — 2026-07-06: ni@tiosquare.com added to the access allowlist + invited via Clerk.
 * 3.12 — 2026-07-06: unixtech7@gmail.com added to the access allowlist + invited via Clerk.
 * 3.13 — 2026-07-06: model picker + all engine-name displays removed from the UI (selection not exposed yet).
 * 3.14 — 2026-07-06: local-first PDFs — the browser reads the text layer (pdf.js), auto-splits, and indexes parts under ONE source; converter only for true scans.
 * 3.15 — 2026-07-06: upload rows show size · detected pages · live phase + conservative ETA under the filename.
 * 3.16 — 2026-07-06: exact-mention lexical lane — "is X mentioned" / quoted / proper-noun questions get an exhaustive literal scan of the wired sources injected beside semantic retrieval (the Kathy fix).
 * 3.17 — 2026-07-06: metering + abuse layer — plan caps (questions/month gate on query+opine, live storage gate at ingest), usage_counters table, managed spend-capped OpenRouter sub-keys for non-BYOK scopes, public embed/API per-IP throttle + durable per-connection daily budget.
 * 3.18 — 2026-07-06: Health page shows "This month" usage meters (questions vs cap, documents added, storage vs cap, plan badge); vendor name scrubbed from the Health header (stack privacy).
 * 3.19 — 2026-07-06: Health split into Admin/User views (owner toggle previews exactly what a user sees); index-wide totals now owner-only in /api/usage (were in every response); "Namespaces · one per project" card corrected to "Projects · all in your private space".
 * 3.20 — 2026-07-06: white brand mark sits directly on the olive rail (no tile box, Make.com-style); rail project-switcher tile keeps a fixed olive-glass look in both themes.
 * 3.21 — 2026-07-06: Health page scrolls as one column — the grown header (This-month + admin table) was crushing the per-source list's scroll area to zero height.
 * 3.22 — 2026-07-06: Health per-source list shows ALL projects, grouped (active project live + manageable, others read-only snapshots); Sources card counts every project.
 * 3.23 — 2026-07-06: Health organization — sortable sources (name/chunks/size/indexed, click to flip), collapsible project groups (persisted; first visit opens only the current project), search box, per-group chunk/size totals, expand/collapse all.
 * 3.24 — 2026-07-06: pricing plans wired — starter/pro/team caps from the researched cost model (80-90% margin), question CREDITS (ask 1 / research 3 / opine 2), BYOK doubles the allowance, monthly upload gate, starter plan slug.
 * 3.25 — 2026-07-06: managed LLM caps resized to cover FULL credit burn + headroom (starter $2 / pro $8 / team $48) — the credit gate is the limiter customers feel; the dollar cap is only the emergency brake.
 * 3.26 — 2026-07-06: caps re-derived at the WORST legitimate mix (all-research, ~$0.023/credit): starter $3 / pro $13 / team $75 — the internal dollar brake can never bind a legitimate month.
 * 3.27 — 2026-07-06: overage top-up packs — `topup_questions` counter adds to the monthly allowance at both question gates; owner-only /api/admin/grant-credits grants packs ($10/100, $39/500); storage marketed in PAGES (~10 vectors/page measured).
 * 3.28 — 2026-07-06: figure billing design pinned — a figure = 2 pages of storage, 50 figures = 1 upload credit (constants in plans.ts; extraction feature itself queued).
 * 3.29 — 2026-07-06: 📋 Forms — smart form filling: fillable PDF's fields read in-browser (pdf-lib, the PDF never leaves the tab), answered from wired sources via /api/fill-form (one batched JSON generation, 3 credits), values written back locally with per-field evidence + editable review.
 * 3.30 — 2026-07-10: walkthrough UX pass — desktop top bar removed (controls live at the rail's bottom, wordmark under the logo); rail is ONE flat dark olive with pure-white labels + technical aliases (RAG/prompts/artifacts…) and tooltips; Library/Projects rows are single dense lines (the "source ↗" link that hijacked clicks to a parked domain is gone); Agents cards edit on text-click; Forms steps sit side-by-side; highlight-to-copy everywhere (SelectCopy).
 * 3.31 — 2026-07-13: click-to-add bank pills — clicking a bank's pill opens a popup that adds + WIRES content straight into that lane: Library → upload sources (one loose chip if single, a box if several), Draft → upload/paste one working doc → artifact, Examples → add a sample → reference, Persona → pick a saved agent → robot. New pillAdd store signal + board-canvas host; UploadDialog gained onSourcesAdded; new AgentPickDialog.
 * 3.32 — 2026-07-15: PROGRESSIVE voiceover — read-aloud now starts within seconds instead of after the whole answer synthesizes. Shared lib/rag/board/voiceover.ts plans a SHORT first chunk + larger prefetched chunks, plays them in order through one <audio> element; same Gemini-TTS engine/voice (no new cost, no new credential). The 🔈 button is now a toggle — click again to STOP, which aborts pending chunk synths (you don't pay for audio you don't hear). Route gained a chunk flag (inline data URL, no Blob litter). Wired in both brain-node + research-overlay.
 * 3.33 — 2026-07-19: voiceover SILENCE fix — 3.32's prefetch fired 3 chunk requests at once, but the Make TTS webhook handles ONE call at a time → bursts returned 502 (logs: mixed 200/502); when chunk 0 was a 502 you heard nothing. Now chunks synthesize strictly ONE AT A TIME in order (producer/consumer; a chunk's audio far outlasts its synth time, so playback stays gapless without concurrency) + one retry per chunk for transient 502s.
 * 3.34 — 2026-07-19: voiceover "reads 2 lines then stops" fix — 3.33's producer/consumer used a hand-rolled wake latch with a LOST-WAKEUP race: if a chunk finished synthesizing in the gap between the consumer's ready-check and its sleep, the signal was lost and playback stalled after the first clip (runtime logs were all 200s, proving synth was fine and the stall was client-side). Replaced the latch with a promise CHAIN — synth stays serialized one-at-a-time (keeps the 3.33 no-burst fix) but playback awaits plain promises, which cannot lose a wakeup. Also clears onended/onerror on settle so a stale event from the previous src can't end a clip early.
 * 3.35 — 2026-07-19: voiceover RAMPED chunks — the gap after the first clip was pipeline math: a 220-char opener (~17s of audio) can't cover a 1200-char follow-up's ~35s synth on the single-call webhook, so playback ran dry ("two lines… long gap… the rest"). Chunk sizes now ramp 220→350→500→700→1000→1200: each clip's playback time covers the next chunk's synth time, so the buffer grows instead of collapsing — fast start AND continuous read.
 * 3.36 — 2026-07-19: 🔊 AUDIO MODE — a toggle on the Answers Bank ("Audio", next to Cited only): while ON, every arriving answer reads itself aloud automatically (hands-free listening), in the bank card AND research mode. Autoplay policy handled via a shared singleton <audio> element unlocked with 0.1s of silence during the toggle click (an element that played in a gesture may play again without one); the singleton also enforces one voice at a time app-wide. Voiceovers now speak PROSE only (sup footnotes, [n] markers, HTML stripped). Flag persists per bank in node data.
 */
export const BUILD_VERSION = '3.36';
