import { Citation, MediaItem } from '../types';

interface RawCitation {
  source_name: string;
  source_id: string;
  snippet: string;
  score: number;
  /** schema v2 — present once chunking lands. */
  page?: number | null;
  timestamp?: string | null;
}

export interface AskResult {
  answer: string;
  citations: Citation[];
  live: boolean;
  /** True when retrieval was weak/empty — the answer may not be grounded in
   *  the wired sources (the no-match honesty guardrail). */
  noMatch: boolean;
  /** Best retrieved similarity score (0–1), or null if nothing came back. */
  topScore: number | null;
  /** Follow-up questions generated by Make, shown as clickable chips. */
  suggestedQuestions: string[];
}

/**
 * Extract the FIRST [M:SS] timestamp marker embedded in a chunk snippet.
 * YouTube captions interleave these every ~15s during chunking.
 */
function extractTimestamp(snippet: string): { locator: string; startSec: number } | null {
  const m = snippet.match(/\[(\d+):(\d{2})\]/);
  if (!m) return null;
  const mins = parseInt(m[1], 10);
  const secs = parseInt(m[2], 10);
  return { locator: `${m[1]}:${m[2]}`, startSec: mins * 60 + secs };
}

/** Build a YouTube watch URL with a ?t= seek offset from the source URL. */
function youtubeJumpUrl(
  source: string | undefined,
  startSec: number
): string | undefined {
  if (!source) return undefined;
  const m = source.match(/(?:v=|youtu\.be\/|shorts\/)([a-zA-Z0-9_-]{11})/);
  if (!m) return undefined;
  return `https://www.youtube.com/watch?v=${m[1]}&t=${startSec}`;
}

/**
 * Parse the ORDERED raw citation array from Make — NOT deduped, original order
 * preserved, because the self-citation indices the model returns (`used_sources`)
 * are 1-based positions into THIS exact array (it's the same `{{14.json}}` the
 * answer/attribution model saw). Handles both response shapes:
 *   - raw_citations: full JSON string from module 14 (TransformToJSON). Preferred.
 *   - citations: the old scalar-collapsed single-item array (fallback).
 */
/**
 * Make's WebhookRespond sometimes wraps the answer payload as
 * `[{ json: "<stringified payload>" }]` or `{ json: "<stringified>" }`
 * (a TransformToJSON bundle) instead of the raw `{ answer, citations,
 * raw_citations, ... }` object — a re-import can flip this. Unwrap to the real
 * object so data.answer / data.raw_citations resolve and inline [n] markers
 * become clickable footnotes again. No-op when the response is already flat.
 */
function unwrapMakeJson(d: any): any {
  let cur: any = d;
  for (let i = 0; i < 4 && cur != null; i++) {
    if (Array.isArray(cur)) {
      cur = cur[0];
      continue;
    }
    if (
      typeof cur === 'object' &&
      cur.answer === undefined &&
      typeof cur.json === 'string'
    ) {
      try {
        cur = JSON.parse(cur.json);
        continue;
      } catch {
        break;
      }
    }
    break;
  }
  return cur && typeof cur === 'object' && !Array.isArray(cur) ? cur : d;
}

function parseRawCitations(data: {
  citations?: RawCitation[];
  raw_citations?: string | RawCitation[];
}): RawCitation[] {
  let raw: RawCitation[] = [];
  if (data.raw_citations) {
    try {
      const parsed =
        typeof data.raw_citations === 'string'
          ? (JSON.parse(data.raw_citations) as unknown)
          : data.raw_citations;
      if (Array.isArray(parsed)) {
        raw = (parsed as Array<Record<string, unknown>>).map((item) => {
          if (item.source_id) return item as unknown as RawCitation;
          // Aggregator shape: {score, metadata:{source_id,source_name,text}}
          const meta = (item.metadata ?? {}) as Record<string, unknown>;
          return {
            score: item.score as number,
            source_id: meta.source_id as string,
            source_name: meta.source_name as string,
            snippet: (meta.text ?? meta.snippet ?? '') as string,
          } as RawCitation;
        });
      }
    } catch {
      /* fall through to data.citations */
    }
  }
  if (raw.length === 0 && Array.isArray(data.citations)) {
    raw = data.citations;
  }
  return raw.filter((c) => c && c.source_id);
}

/** Dedup a raw list by (source_id + first 80 chars of snippet). */
function dedupeRaw(raw: RawCitation[]): RawCitation[] {
  const seen = new Set<string>();
  return raw.filter((c) => {
    const key = `${c.source_id}::${(c.snippet ?? '').trim().slice(0, 80)}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

const NARRATIVE_KEYS = [
  'summary',
  'summary_text',
  'overall_topic',
  'topic_overview',
  'structure_and_main_points',
  'key_points',
  'key_takeaways'
];

function pullNarrative(o: unknown, out: string[]): void {
  if (o == null) return;
  if (typeof o === 'string') {
    out.push(o);
    return;
  }
  if (Array.isArray(o)) {
    o.forEach((x) => pullNarrative(x, out));
    return;
  }
  if (typeof o === 'object') {
    const rec = o as Record<string, unknown>;
    for (const k of NARRATIVE_KEYS) if (k in rec) pullNarrative(rec[k], out);
    if (out.length === 0 && typeof rec.title === 'string') out.push(rec.title);
  }
}

/**
 * Some chunk text is a JSON-encoded summary object/array, e.g.
 * `{"title":"…","summary":"…"}` or `{"summary":["…","…"]}`. Citation snippets
 * must show the human prose — never the raw JSON braces/keys.
 */
function cleanSnippet(raw: string | undefined): string {
  const s = (raw ?? '').trim();
  if (!s || (s[0] !== '{' && s[0] !== '[')) return s;
  try {
    const out: string[] = [];
    pullNarrative(JSON.parse(s), out);
    const text = out.filter(Boolean).join(' ').replace(/\s+/g, ' ').trim();
    if (text) return text;
  } catch {
    // Malformed JSON (some chunks carry trailing junk): pull the summary value.
    const m = s.match(
      /"(?:summary|summary_text|overall_topic)"\s*:\s*"((?:[^"\\]|\\.)*)"/
    );
    if (m)
      return m[1]
        .replace(/\\[nrt]/g, ' ')
        .replace(/\\"/g, '"')
        .replace(/\s+/g, ' ')
        .trim();
  }
  return s;
}

/** Enrich one raw citation into the typed Citation (score, timestamp, jumpUrl). */
function toCitation(c: RawCitation, byId: Map<string, MediaItem>): Citation {
  const m = byId.get(c.source_id);
  const ts = extractTimestamp(c.snippet ?? '');
  const startSec = ts?.startSec;
  const jumpUrl =
    startSec !== undefined && m?.type === 'youtube'
      ? youtubeJumpUrl(m.source, startSec)
      : undefined;
  const score = typeof c.score === 'number' ? c.score : undefined;
  const locator = ts
    ? ts.locator
    : c.page
      ? `p. ${c.page}`
      : score !== undefined
        ? `${Math.round(score * 100)}%`
        : '';
  return {
    mediaId: c.source_id,
    mediaName: c.source_name || m?.name || c.source_id,
    type: m?.type ?? 'document',
    locator,
    snippet: cleanSnippet(c.snippet),
    score,
    startSec,
    jumpUrl,
  } satisfies Citation;
}

/**
 * SELF-CITATION (preferred): the answer/attribution model returns the 1-based
 * indices of the chunks it actually used (`used_sources`, e.g. "3" or "1,3").
 * We pick exactly those chunks from the ordered raw array — no guessing.
 * Returns [] if the field is absent/empty/unparseable so the caller can fall
 * back to the lexical filter.
 */
function selectByUsedSources(
  ordered: RawCitation[],
  usedSources: unknown,
  byId: Map<string, MediaItem>
): Citation[] {
  if (usedSources === undefined || usedSources === null) return [];
  // Accept a native array of numbers, or a string like "1,3" / "[1, 3]".
  let nums: number[] = [];
  if (Array.isArray(usedSources)) {
    nums = usedSources
      .map((n) => parseInt(String(n), 10))
      .filter((n) => Number.isFinite(n));
  } else if (typeof usedSources === 'string') {
    nums = (usedSources.match(/\d+/g) ?? []).map((s) => parseInt(s, 10));
  }
  if (nums.length === 0) return [];
  const picked = nums
    .map((i) => ordered[i - 1]) // 1-based → 0-based
    .filter((c): c is RawCitation => !!c && !!c.source_id);
  if (picked.length === 0) return [];
  return dedupeRaw(picked)
    .sort((a, b) => (b.score ?? 0) - (a.score ?? 0))
    .map((c) => toCitation(c, byId));
}

/**
 * SELF-CITATION, per-claim (preferred when the answer cites chunk NUMBERS):
 * footnotes = exactly the chunks the answer referenced inline ([n] / [n,m]),
 * in order of first appearance, deduped. Each footnote is therefore a DISTINCT
 * chunk that some specific claim cited — so footnote [1] and [2] highlight
 * different passages (the bug the user hit was the model citing source NAMES,
 * which all collapsed to footnote 1). Returns [] when the answer has no numeric
 * citations (then we fall back to used_sources / lexical).
 */
function footnotesFromInlineCitations(
  answer: string,
  ordered: RawCitation[],
  byId: Map<string, MediaItem>
): Citation[] {
  if (!answer) return [];
  // collect cited 1-based raw indices in order of appearance
  const idx: number[] = [];
  for (const m of answer.matchAll(/\[(\d+(?:\s*,\s*\d+)*)\]/g)) {
    for (const s of m[1].split(/[,\s]+/)) {
      const n = parseInt(s, 10);
      if (Number.isFinite(n)) idx.push(n);
    }
  }
  if (idx.length === 0) return [];
  const seen = new Set<string>();
  const picked: RawCitation[] = [];
  for (const i of idx) {
    const c = ordered[i - 1];
    if (!c || !c.source_id) continue;
    const key = `${c.source_id}::${(c.snippet ?? '').trim().slice(0, 80)}`;
    if (seen.has(key)) continue;
    seen.add(key);
    picked.push(c);
  }
  return picked.map((c) => toCitation(c, byId));
}

/** Fallback path: dedup → sort by score → cap 8 → lexical narrowing. */
function buildCitationsFallback(
  ordered: RawCitation[],
  answer: string,
  byId: Map<string, MediaItem>
): Citation[] {
  const cits = dedupeRaw(ordered)
    .sort((a, b) => (b.score ?? 0) - (a.score ?? 0))
    .slice(0, 8)
    .map((c) => toCitation(c, byId));
  return filterToAnswer(cits, answer);
}

const citeKey = (sourceId: string, snippet: string) =>
  `${sourceId}::${(snippet ?? '').trim().slice(0, 80)}`;

const looksHtml = (s: string) =>
  /<\/?(p|div|h[1-6]|ul|ol|li|table|br|strong|em|a|span|mark|section)\b/i.test(s);

/**
 * Turn the answer's inline citation markers into numbered, clickable footnote
 * references — "real book" style. The shown citations ARE the footnotes
 * (numbered 1..K in display order). Markers are matched two ways:
 *   - numeric chunk index, e.g. [4] or [4, 26]  → mapped via the ordered raw
 *     array to the footnote of that chunk (used once answers cite by number);
 *   - source-name, e.g. [test3]                 → mapped to that source's footnote.
 * In an HTML answer each marker becomes <sup class="fn-ref" data-fn="N">N</sup>
 * (the brain wires a click handler to open footnote N). In a plain answer it
 * degrades to a bare [N] so formatting never breaks.
 */
function footnoteAnswer(
  answer: string,
  citations: Citation[],
  ordered: RawCitation[]
): string {
  if (!answer || citations.length === 0) return answer;
  const html = looksHtml(answer);

  const fnByKey = new Map<string, number>();
  const fnByName = new Map<string, number>();
  citations.forEach((c, i) => {
    fnByKey.set(citeKey(c.mediaId, c.snippet), i + 1);
    if (!fnByName.has(c.mediaName)) fnByName.set(c.mediaName, i + 1);
  });
  // raw 1-based chunk index → footnote number (for numeric [n] citations)
  const fnByRawIndex = new Map<number, number>();
  ordered.forEach((r, idx) => {
    const fn = fnByKey.get(citeKey(r.source_id, r.snippet ?? ''));
    if (fn) fnByRawIndex.set(idx + 1, fn);
  });

  // ALWAYS emit a clickable footnote ref (not just for HTML answers) — the
  // marker should be tappable in the text, not just in the list below.
  const ref = (n: number) =>
    `<sup class="fn-ref" data-fn="${n}">${n}</sup>`;

  const withRefs = answer.replace(/\[([^\]\n]{1,60})\]/g, (full, inner: string) => {
    const text = inner.trim();
    // numeric chunk index/indices: [4] or [4, 26]
    if (/^[\d][\d,\s]*$/.test(text)) {
      const fns = text
        .split(/[,\s]+/)
        .map((s) => parseInt(s, 10))
        .filter((n) => Number.isFinite(n))
        .map((n) => fnByRawIndex.get(n))
        .filter((n): n is number => !!n);
      const uniq = [...new Set(fns)];
      return uniq.length ? uniq.map(ref).join('') : ''; // unused chunk → drop
    }
    // source-name marker, e.g. [test3]
    const fn = fnByName.get(text);
    return fn ? ref(fn) : full; // unknown marker → leave as-is
  });

  // HTML answers already route to the HTML renderer. A PLAIN answer that now
  // carries <sup> refs must too — wrap it as minimal HTML (preserving line
  // breaks) so the refs render as clickable superscripts, not literal text.
  if (html || !withRefs.includes('<sup class="fn-ref"')) return withRefs;
  return (
    '<p>' +
    withRefs.replace(/\n{2,}/g, '</p><p>').replace(/\n/g, '<br>') +
    '</p>'
  );
}

// Common words that carry no distinguishing signal — ignored when matching the
// answer against chunks (so "the US creator" doesn't make every chunk "match").
const STOPWORDS = new Set(
  ('the and that this with from they them their what when where which while about'
    + ' have has had will would could should been being your you our are was were'
    + ' into over under than then there here also some such only just more most'
    + ' because they cannot could into onto upon does did done very much many'
    + ' said says according source sources').split(/\s+/)
);

/** Content words (>=4 chars, non-stopword) from a blob of text. */
function contentWords(text: string): string[] {
  const plain = text
    .replace(/<[^>]+>/g, ' ')
    .replace(/&[a-z]+;/gi, ' ')
    .replace(/\[\d+:\d{2}\]/g, ' ')
    .toLowerCase();
  const words = plain.match(/[a-z0-9]{4,}/g) ?? [];
  return words.filter((w) => !STOPWORDS.has(w));
}

/**
 * Keep only the chunks the ANSWER actually drew from. The model cites the
 * source *name* ([test3]) generically, so multi-query retrieval hands back
 * chunks the answer never used. We score each chunk by IDF-weighted overlap
 * with the answer's distinctive words (rare words across the chunk set count
 * more than common ones), then keep the chunks that genuinely support it.
 * Falls back to the unfiltered set if scoring is degenerate (never shows zero).
 */
function filterToAnswer(citations: Citation[], answer: string): Citation[] {
  if (citations.length <= 1) return citations;
  const kws = [...new Set(contentWords(answer))];
  if (kws.length === 0) return citations;

  const N = citations.length;
  const snipWords = citations.map((c) => new Set(contentWords(c.snippet ?? '')));
  // document frequency of each answer-word across the chunk set
  const df = new Map<string, number>();
  for (const kw of kws) {
    let d = 0;
    for (const sw of snipWords) if (sw.has(kw)) d++;
    df.set(kw, d);
  }
  const scoreOf = (i: number) => {
    let s = 0;
    for (const kw of kws) {
      const d = df.get(kw) ?? 0;
      if (d > 0 && snipWords[i].has(kw)) s += Math.log(1 + N / d); // IDF weight
    }
    return s;
  };
  const scored = citations
    .map((c, i) => ({ c, s: scoreOf(i) }))
    .sort((a, b) => b.s - a.s);
  const max = scored[0].s;
  if (max <= 0) return citations.slice(0, 4); // nothing distinctive → keep a few
  // keep chunks within 30% of the best supporter (the genuine sources); the
  // unused chunks score ~0 and fall away. Always keep at least the top one.
  const kept = scored.filter((x) => x.s >= 0.3 * max).map((x) => x.c);
  return kept.length ? kept : [scored[0].c];
}

/**
 * Ask the live RAG backend (Make.com Query scenario via /api/query).
 * The brain's wired connectivity arrives here as source_ids — the Board
 * is a visual source_ids assembler, nothing more.
 */
export async function askBrain(
  question: string,
  items: MediaItem[],
  contextTexts: string[],
  modelId?: string,
  /** 'cited' = answer ONLY from sources; 'hybrid' = sources first, then let
   *  the model fill gaps from its own knowledge (clearly marked). */
  mode: 'cited' | 'hybrid' = 'cited',
  /** Instruction guides from wired prompt pieces (how to answer). */
  guides: string[] = [],
  /** Recent conversation turns (role + plain-text content) so the server can
   *  rewrite a follow-up ("his street") into a standalone retrieval query. */
  history: { role: 'user' | 'assistant'; content: string }[] = [],
  /** Rolling summary of turns older than the verbatim window (long convos). */
  summary = '',
  /** 'detailed' = full pipeline (expander/validator/attribution/memory);
   *  'fast' = lightning path that skips the extra LLM round-trips for speed;
   *  'research' = deepest tier (full pipeline + the heavier GLM answer model
   *  on the Make side). */
  speed: 'fast' | 'detailed' | 'research' = 'detailed',
  /** Wired box ids / everything-hub / project id — lets a "summarize" question
   *  use the precomputed box or project rollup instead of re-synthesizing. */
  clusterIds: string[] = [],
  everything = false,
  projectId?: string
): Promise<AskResult> {
  const res = await fetch('/api/query', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      question,
      source_ids: items.map((m) => m.id),
      context_texts: contextTexts,
      guides,
      model: modelId,
      answer_mode: mode,
      history,
      summary,
      speed,
      cluster_ids: clusterIds,
      everything,
      project_id: projectId
    })
  });

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(err.error ?? `Query failed (${res.status})`);
  }

  const data = unwrapMakeJson(await res.json());

  const suggestedQuestions: string[] = Array.isArray(data.suggestedQuestions)
    ? data.suggestedQuestions.filter(
        (s: unknown) => typeof s === 'string' && s.trim()
      )
    : [];

  // Citations/footnotes are built here from the retrieved chunks — FREE,
  // app-side, no extra LLM — so both fast and detailed get the same clickable
  // footnotes. (Fast's speed win lives in the Make route + skipped server
  // stages, not in dropping citations.)
  const byId = new Map(items.map((m) => [m.id, m]));

  // Citations = the chunks the answer actually used. PREFERRED: the model's own
  // self-citation (`used_sources` = 1-based chunk indices from the Make
  // attribution step) — deterministic truth, robust to paraphrasing. FALLBACK
  // (no `used_sources` field yet): the lexical IDF-overlap narrowing.
  const ordered = parseRawCitations(data);
  // PREFERRED: footnotes = exactly the chunks the answer cited inline by number
  // (per-claim accuracy). Falls back to the attribution set (used_sources), then
  // the lexical narrowing, when the answer doesn't cite by number.
  const inline = footnotesFromInlineCitations(data.answer ?? '', ordered, byId);
  const used = inline.length
    ? inline
    : selectByUsedSources(ordered, data.used_sources, byId);
  const citations = used.length
    ? used
    : buildCitationsFallback(ordered, data.answer ?? '', byId);

  // Numbered footnotes: rewrite inline [name]/[n] markers → clickable [N]
  // refs that line up with the citation list below the answer.
  const answer = footnoteAnswer(data.answer ?? '', citations, ordered);

  return {
    answer,
    citations,
    live: true,
    noMatch: Boolean(data.noMatch),
    topScore: typeof data.topScore === 'number' ? data.topScore : null,
    suggestedQuestions
  };
}

/**
 * Opine — the wired corpus reasons ABOUT an artifact (the right plug, carried
 * whole, never indexed) with optional reference samples and robot `guides`.
 * Calls /api/opine (in-code two-pass Conductor), which returns the SAME response
 * shape as /api/query — so the entire footnote/citation pipeline below is reused
 * verbatim. `citations:'off'` makes the server return no raw_citations → clean
 * prose with no footnotes (still grounded). `grounding` reuses the brain's
 * cited/hybrid dial.
 */
export async function opineBrain(
  instruction: string,
  items: MediaItem[],
  artifact: { title?: string; url?: string; content: string },
  references: Array<{ title?: string; content: string }>,
  guides: string[] = [],
  citations: 'on' | 'off' = 'on',
  grounding: 'cited' | 'hybrid' = 'cited',
  history: { role: 'user' | 'assistant'; content: string }[] = [],
  projectId?: string
): Promise<AskResult> {
  const res = await fetch('/api/opine', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      instruction,
      artifact,
      references,
      source_ids: items.map((m) => m.id),
      guides,
      citations,
      grounding,
      history,
      project_id: projectId
    })
  });

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(err.error ?? `Opine failed (${res.status})`);
  }

  const data = unwrapMakeJson(await res.json());
  const byId = new Map(items.map((m) => [m.id, m]));

  // Same app-side citation/footnote build as askBrain. When citations are OFF the
  // server sends no raw_citations → ordered is empty → no footnotes, answer as-is.
  const ordered = parseRawCitations(data);
  const inline = footnotesFromInlineCitations(data.answer ?? '', ordered, byId);
  const used = inline.length
    ? inline
    : selectByUsedSources(ordered, data.used_sources, byId);
  const built = used.length
    ? used
    : buildCitationsFallback(ordered, data.answer ?? '', byId);
  const answer = footnoteAnswer(data.answer ?? '', built, ordered);

  return {
    answer,
    citations: built,
    live: true,
    noMatch: Boolean(data.noMatch),
    topScore: typeof data.topScore === 'number' ? data.topScore : null,
    suggestedQuestions: []
  };
}
