import { Citation, MediaItem } from '../types';

interface RawCitation {
  source_name: string;
  source_id: string;
  snippet: string;
  score: number;
  /** schema v2 — present once chunking lands. */
  page?: number | null;
  timestamp?: string | null;
}

export interface AskResult {
  answer: string;
  citations: Citation[];
  live: boolean;
  /** True when retrieval was weak/empty — the answer may not be grounded in
   *  the wired sources (the no-match honesty guardrail). */
  noMatch: boolean;
  /** Best retrieved similarity score (0–1), or null if nothing came back. */
  topScore: number | null;
  /** Follow-up questions generated by Make, shown as clickable chips. */
  suggestedQuestions: string[];
}

/**
 * Extract the FIRST [M:SS] timestamp marker embedded in a chunk snippet.
 * YouTube captions interleave these every ~15s during chunking.
 */
function extractTimestamp(snippet: string): { locator: string; startSec: number } | null {
  const m = snippet.match(/\[(\d+):(\d{2})\]/);
  if (!m) return null;
  const mins = parseInt(m[1], 10);
  const secs = parseInt(m[2], 10);
  return { locator: `${m[1]}:${m[2]}`, startSec: mins * 60 + secs };
}

/** Build a YouTube watch URL with a ?t= seek offset from the source URL. */
function youtubeJumpUrl(
  source: string | undefined,
  startSec: number
): string | undefined {
  if (!source) return undefined;
  const m = source.match(/(?:v=|youtu\.be\/|shorts\/)([a-zA-Z0-9_-]{11})/);
  if (!m) return undefined;
  return `https://www.youtube.com/watch?v=${m[1]}&t=${startSec}`;
}

/**
 * Parse raw citations from Make and enrich them into typed Citation objects.
 * Handles the two Make response shapes:
 *   - raw_citations: the full JSON string from module 14 (TransformToJSON of
 *     the aggregator array) — available once the user adds the field to
 *     CreateJSON module 10. This is the preferred path.
 *   - citations: the old scalar-collapsed single-item array (fallback).
 *
 * Applies: dedup by (source_id + snippet key) → sort desc by score → cap 8.
 */
function buildCitations(
  data: {
    citations?: RawCitation[];
    raw_citations?: string | RawCitation[];
  },
  byId: Map<string, MediaItem>
): Citation[] {
  // Prefer the full aggregator array (all N retrieved chunks).
  let raw: RawCitation[] = [];
  if (data.raw_citations) {
    try {
      const parsed =
        typeof data.raw_citations === 'string'
          ? (JSON.parse(data.raw_citations) as unknown)
          : data.raw_citations;
      if (Array.isArray(parsed)) {
        // TransformToJSON wraps each element as {score, metadata:{...}}.
        // Map to a flat RawCitation if necessary.
        raw = (parsed as Array<Record<string, unknown>>).map((item) => {
          if (item.source_id) return item as unknown as RawCitation;
          // Aggregator shape: {score, metadata:{source_id,source_name,text}}
          const meta = (item.metadata ?? {}) as Record<string, unknown>;
          return {
            score: item.score as number,
            source_id: meta.source_id as string,
            source_name: meta.source_name as string,
            snippet: (meta.text ?? meta.snippet ?? '') as string,
          } as RawCitation;
        });
      }
    } catch {
      /* fall through to data.citations */
    }
  }
  // Fallback: the collapsed single-item (or partial) list from CreateJSON.
  if (raw.length === 0 && Array.isArray(data.citations)) {
    raw = data.citations;
  }

  // Dedup: same chunk can surface from multiple query expansions.
  const seen = new Set<string>();
  const deduped = raw
    .filter((c) => {
      if (!c?.source_id) return false;
      const key = `${c.source_id}::${(c.snippet ?? '').trim().slice(0, 80)}`;
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    })
    .sort((a, b) => (b.score ?? 0) - (a.score ?? 0))
    .slice(0, 8);

  return deduped.map((c) => {
    const m = byId.get(c.source_id);
    const ts = extractTimestamp(c.snippet ?? '');
    const startSec = ts?.startSec;
    const jumpUrl =
      startSec !== undefined && m?.type === 'youtube'
        ? youtubeJumpUrl(m.source, startSec)
        : undefined;

    const score = typeof c.score === 'number' ? c.score : undefined;
    const locator = ts
      ? ts.locator
      : c.page
        ? `p. ${c.page}`
        : score !== undefined
          ? `${Math.round(score * 100)}%`
          : '';

    return {
      mediaId: c.source_id,
      mediaName: c.source_name || m?.name || c.source_id,
      type: m?.type ?? 'document',
      locator,
      snippet: c.snippet ?? '',
      score,
      startSec,
      jumpUrl,
    } satisfies Citation;
  });
}

// Common words that carry no distinguishing signal — ignored when matching the
// answer against chunks (so "the US creator" doesn't make every chunk "match").
const STOPWORDS = new Set(
  ('the and that this with from they them their what when where which while about'
    + ' have has had will would could should been being your you our are was were'
    + ' into over under than then there here also some such only just more most'
    + ' because they cannot could into onto upon does did done very much many'
    + ' said says according source sources').split(/\s+/)
);

/** Content words (>=4 chars, non-stopword) from a blob of text. */
function contentWords(text: string): string[] {
  const plain = text
    .replace(/<[^>]+>/g, ' ')
    .replace(/&[a-z]+;/gi, ' ')
    .replace(/\[\d+:\d{2}\]/g, ' ')
    .toLowerCase();
  const words = plain.match(/[a-z0-9]{4,}/g) ?? [];
  return words.filter((w) => !STOPWORDS.has(w));
}

/**
 * Keep only the chunks the ANSWER actually drew from. The model cites the
 * source *name* ([test3]) generically, so multi-query retrieval hands back
 * chunks the answer never used. We score each chunk by IDF-weighted overlap
 * with the answer's distinctive words (rare words across the chunk set count
 * more than common ones), then keep the chunks that genuinely support it.
 * Falls back to the unfiltered set if scoring is degenerate (never shows zero).
 */
function filterToAnswer(citations: Citation[], answer: string): Citation[] {
  if (citations.length <= 1) return citations;
  const kws = [...new Set(contentWords(answer))];
  if (kws.length === 0) return citations;

  const N = citations.length;
  const snipWords = citations.map((c) => new Set(contentWords(c.snippet ?? '')));
  // document frequency of each answer-word across the chunk set
  const df = new Map<string, number>();
  for (const kw of kws) {
    let d = 0;
    for (const sw of snipWords) if (sw.has(kw)) d++;
    df.set(kw, d);
  }
  const scoreOf = (i: number) => {
    let s = 0;
    for (const kw of kws) {
      const d = df.get(kw) ?? 0;
      if (d > 0 && snipWords[i].has(kw)) s += Math.log(1 + N / d); // IDF weight
    }
    return s;
  };
  const scored = citations
    .map((c, i) => ({ c, s: scoreOf(i) }))
    .sort((a, b) => b.s - a.s);
  const max = scored[0].s;
  if (max <= 0) return citations.slice(0, 4); // nothing distinctive → keep a few
  // keep chunks within 30% of the best supporter (the genuine sources); the
  // unused chunks score ~0 and fall away. Always keep at least the top one.
  const kept = scored.filter((x) => x.s >= 0.3 * max).map((x) => x.c);
  return kept.length ? kept : [scored[0].c];
}

/**
 * Ask the live RAG backend (Make.com Query scenario via /api/query).
 * The brain's wired connectivity arrives here as source_ids — the Board
 * is a visual source_ids assembler, nothing more.
 */
export async function askBrain(
  question: string,
  items: MediaItem[],
  contextTexts: string[],
  modelId?: string,
  /** 'cited' = answer ONLY from sources; 'hybrid' = sources first, then let
   *  the model fill gaps from its own knowledge (clearly marked). */
  mode: 'cited' | 'hybrid' = 'cited',
  /** Instruction guides from wired prompt pieces (how to answer). */
  guides: string[] = [],
  /** Recent conversation turns (role + plain-text content) so the server can
   *  rewrite a follow-up ("his street") into a standalone retrieval query. */
  history: { role: 'user' | 'assistant'; content: string }[] = [],
  /** Rolling summary of turns older than the verbatim window (long convos). */
  summary = ''
): Promise<AskResult> {
  const res = await fetch('/api/query', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      question,
      source_ids: items.map((m) => m.id),
      context_texts: contextTexts,
      guides,
      model: modelId,
      answer_mode: mode,
      history,
      summary
    })
  });

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(err.error ?? `Query failed (${res.status})`);
  }

  const data = await res.json();
  const byId = new Map(items.map((m) => [m.id, m]));

  // All retrieved+deduped chunks, then narrowed to the ones the answer
  // actually used (multi-query retrieval over-fetches; the answer often rests
  // on a single chunk — don't list 6 "sources" it never touched).
  const citations = filterToAnswer(buildCitations(data, byId), data.answer ?? '');

  const suggestedQuestions: string[] = Array.isArray(data.suggestedQuestions)
    ? data.suggestedQuestions.filter(
        (s: unknown) => typeof s === 'string' && s.trim()
      )
    : [];

  return {
    answer: data.answer,
    citations,
    live: true,
    noMatch: Boolean(data.noMatch),
    topScore: typeof data.topScore === 'number' ? data.topScore : null,
    suggestedQuestions
  };
}
