import { Citation, MediaItem } from '../types';

interface RawCitation {
  source_name: string;
  source_id: string;
  snippet: string;
  score: number;
  /** schema v2 — present once chunking lands. */
  page?: number | null;
  timestamp?: string | null;
}

export interface AskResult {
  answer: string;
  citations: Citation[];
  live: boolean;
  /** True when retrieval was weak/empty — the answer may not be grounded in
   *  the wired sources (the no-match honesty guardrail). */
  noMatch: boolean;
  /** Best retrieved similarity score (0–1), or null if nothing came back. */
  topScore: number | null;
  /** Follow-up questions generated by Make, shown as clickable chips. */
  suggestedQuestions: string[];
}

/**
 * Ask the live RAG backend (Make.com Query scenario via /api/query).
 * The brain's wired connectivity arrives here as source_ids — the Board
 * is a visual source_ids assembler, nothing more.
 */
export async function askBrain(
  question: string,
  items: MediaItem[],
  contextTexts: string[],
  modelId?: string,
  /** 'cited' = answer ONLY from sources; 'hybrid' = sources first, then let
   *  the model fill gaps from its own knowledge (clearly marked). */
  mode: 'cited' | 'hybrid' = 'cited',
  /** Instruction guides from wired prompt pieces (how to answer). */
  guides: string[] = []
): Promise<AskResult> {
  const res = await fetch('/api/query', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      question,
      source_ids: items.map((m) => m.id),
      context_texts: contextTexts,
      guides,
      model: modelId,
      answer_mode: mode
    })
  });

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(err.error ?? `Query failed (${res.status})`);
  }

  const data = await res.json();
  const byId = new Map(items.map((m) => [m.id, m]));

  const citations: Citation[] = (data.citations as RawCitation[]).map((c) => {
    const m = byId.get(c.source_id);
    return {
      mediaId: c.source_id,
      mediaName: c.source_name || m?.name || c.source_id,
      type: m?.type ?? 'document',
      locator: c.page
        ? `p. ${c.page}`
        : c.timestamp
          ? c.timestamp
          : `${Math.round((c.score ?? 0) * 100)}% match`,
      snippet: c.snippet ?? ''
    };
  });

  const suggestedQuestions: string[] = Array.isArray(data.suggestedQuestions)
    ? data.suggestedQuestions.filter(
        (s: unknown) => typeof s === 'string' && s.trim()
      )
    : [];

  return {
    answer: data.answer,
    citations,
    live: true,
    noMatch: Boolean(data.noMatch),
    topScore: typeof data.topScore === 'number' ? data.topScore : null,
    suggestedQuestions
  };
}
